### ISSUE TITLE
ForwardGeocodeResponse is null on iOS 

### ISSUE THREAD

**Issue by pmukherj** [mapbox/mapbox-unity-sdk#359] opened 2017-11-13 18:53 UTC
Hello, 

This issue might be more server-side then with the API but I thought I'd post it here to see if anyone else has had this issue. When I send a geocode request with a space in it, I get a null response but only when its compiled into iOS (it works fine in the Unity editor).  Bit of my code snippet below:

```
void getResponse (string text) {
	ForwardGeocodeResource resource = new ForwardGeocodeResource (text);

	if (m_gpsManager.m_locEnabled) {
		resource.Proximity = new Vector2d (m_gpsManager.m_lat, m_gpsManager.m_lon); 
	}
	Mapbox.Unity.MapboxAccess.Instance.Geocoder.Geocode (resource, AutoCompleteRes);
}

void AutoCompleteRes(ForwardGeocodeResponse res) {
        if (res == null) {
		Debug.Log ("Mapbox returned null");
		return;
	}
       //Do useful things with response
}

getResponse("Oakland"); //works fine
getResponse("2524 Kingston Cr"); //returns null

```

**Comment by david-rhodes** [comment] 2017-11-16 04:11
@pmukherj I saw this once a long time ago. It had something to do with HTTP access/support for iOS. If I recall, Xcode did give me logs proving as much. If you could post your logs and any other details about the device/OS version, that would be helpful. Thanks!

**Comment by pmukherj** [comment] 2017-11-16 17:40
You are correct @david-rhodes. I did see the two HTTP/HTTPS related errors/warnings below, but was confused as to why it would work fine w/ spaces. 

This is on iOS11.1 + iPhone7plus. 

>  You are using download over http. Currently Unity adds NSAllowsArbitraryLoads to Info.plist to simplify transition, but it will be removed soon. Please consider updating to https.

2017-11-16 12:33:50.066237-0500 arkitscene[2223:607256] NSURLConnection finished with error - code -1002

I can post the full logs here as well, though there is a whole bunch of other app related garbage in there.

**Comment by david-rhodes** [comment] 2017-11-16 17:43
cc @mapbox/unity @boundsj Any ideas why such requests would break with spaces on iOS?

**Comment by BergWerkGIS** [comment] 2017-11-17 11:15
> You are using download over **http**.

Hm, no idea where an error about `http` could be coming from.
https://docs.unity3d.com/ScriptReference/PlayerSettings.iOS-allowHTTPDownload.html

* All our URLs have http**s**: [`mapbox-sdk-cs/Utils/Constants.cs`](https://github.com/mapbox/mapbox-unity-sdk/blob/5604971c5512c16cf68c497069735bcc07384b88/sdkproject/Assets/Mapbox/Core/mapbox-sdk-cs/Utils/Constants.cs)
* Query strings are [properly encoded](https://github.com/mapbox/mapbox-unity-sdk/blob/5604971c5512c16cf68c497069735bcc07384b88/sdkproject/Assets/Mapbox/Core/mapbox-sdk-cs/Geocoding/ForwardGeocodeResource.cs#L162)
Verified via logging requests with an external tool (in the Editor on Windows 😏)
![image](https://user-images.githubusercontent.com/4549888/32944698-ba101602-cb90-11e7-9bb9-63d7e53c82ac.png)

**Comment by david-rhodes** [comment] 2017-11-17 15:57
FWIW, I just tested the exact geocode above that did not work ("2524 Kingston Cr") on my iPhone 6S (iOS 11.2) and got results as expected. Something fishy here.

**Comment by pmukherj** [comment] 2017-11-17 16:30
Just to confirm, this worked fine for you? I'll test it on an iPhone 6s here as well then. Also, FYI, I'm on Unity 2017.2.0f3. You mind sharing your Unity versions, I want to make sure that isn't the issue.

**Comment by david-rhodes** [comment] 2017-11-17 16:41
Yep--worked fine. That was with Unity 2017.1.

**Comment by david-rhodes** [comment] 2017-11-27 18:55
Any updates here @pmukherj?

**Comment by pmukherj** [comment] 2017-12-01 18:54
I've checked it on iPhone 7 and 7plus. Tried multiple versions of Xcode. All gave the same broken result. I'm trying to test it on an iPhone 6 and earlier versions of Unity next. I'll try 2017.1.

**Comment by david-rhodes** [comment] 2017-12-01 18:57
Thanks--please let us know your results! Very interested to know if this is because of Unity version differences.

**Comment by pmukherj** [comment] 2017-12-01 21:47
No dice on 2017.1. 

Mapbox returned something
Mapbox.Geocoding.<Geocode>c__AnonStorey1`1:<>m__0(Response)
Mapbox.Platform.<proxyResponse>c__AnonStorey1:<>m__0(Response)
Mapbox.Unity.Utilities.<DoRequest>c__Iterator0:MoveNext()
Mapbox.Unity.Utilities.Routine:MoveNext()
Mapbox.Unity.Utilities.Routine:.ctor(IEnumerator)
Mapbox.Unity.Utilities.Runnable:Run(IEnumerator)
Mapbox.Unity.Utilities.HTTPRequest:.ctor(String, Action`1, Int32)
Mapbox.Platform.IAsyncRequestFactory:CreateRequest(String, ActionMapbox.Platform.FileSource:proxyResponse(String, Action`1, Int32, CanonicalTileId, String)
Mapbox.Platform.FileSource:Request(String, Action`1, Int32, CanonicalTileId, String)
Mapbox.Geocoding.Geocoder:Geocode(GeocodeResource`1, Action`1)
Mapbox returned null
Mapbox.Geocoding.<Geocode>c__AnonStorey1`1:<>m__0(Response)
Mapbox.Platform.<proxyResponse>c__AnonStorey1:<>m__0(Response)
Mapbox.Unity.Utilities.<DoRequest>c__Iterator0:MoveNext()
Mapbox.Unity.Utilities.Routine:MoveNext()

Same problem. I'm a little suspicious of this being an iPhone model (6 vs. 7) problem, its more likely to be related to my phone being on iOS beta. Can you confirm that you were not on the beta?

**Comment by david-rhodes** [comment] 2017-12-01 22:25
@pmukherj Oh... Are you using `MapboxAccess.Geocoder` to do your geocoding queries? If not, I recommend that you do so.

It looks like your request is going through our request factory, which is actually intended to be used for tiles (exclusively).

**Comment by pmukherj** [comment] 2017-12-01 22:35
I am, AFAIK, my call is specifically
`Mapbox.Unity.MapboxAccess.Instance.Geocoder.Geocode (resource, AutoCompleteRes)`
I assumed that goes through` MapboxAccess.Geocoder`.

**Comment by david-rhodes** [comment] 2017-12-01 23:07
Ah, I was mistaken. We will try to reproduce again. I was on beta iOS 11.2 last I tested.

**Comment by david-rhodes** [comment] 2017-12-05 00:17
@pmukherj Please do me a favor and test this geocode without setting the `proximity`.

**Comment by apavani** [comment] 2017-12-05 19:32
@pmukherj We couldn't reproduce the issue even when we set the proximity. Probably it's something else that is causing the issue. If you have more specific steps to reproduce, that would be helpful.

**Comment by pmukherj** [comment] 2017-12-05 20:53
Yea I removed the proximity and still having the issue. I'm trying to find a situation (combination of  Unity, XCode or iOS) where this *doesn't* happen. My best guess is that it is a quirk of the specific iOS Beta I'm running because again, it runs fine on the Unity Editor. I'm going to try and get to a regular (non-beta, or stable beta) of iOS and test again.

**Comment by david-rhodes** [comment] 2017-12-14 17:15
@pmukherj Any updates after testing on different, non-beta devices?

**Comment by MiroMuse** [comment] 2018-01-03 18:32
Closing this issue for now; @pmukherj let us know if you need any other help.

**Closed by MiroMuse** 2018-01-03 18:32 UTC
Labels: bug, help wanted, support
