### ISSUE TITLE
Location doesn't update at start (iOS)

### ISSUE THREAD

**Issue by mecadiego113** [mapbox/mapbox-unity-sdk#384] opened 2017-11-22 17:11 UTC
Hello again mapboxers!

I think I found a bug related with map initialization and location provider.
`InitializeMapWithLocationProvider` uses the device location services to initialize the map with the player position (latitude and longitude).
But, on iPhone, sometimes we don't receive a location update, so the map won't initialize.

Is this a known platform bug or am I doing something wrong?

**Comment by david-rhodes** [comment] 2017-11-22 17:16
Check in your OS application settings that location is enabled. Also, are you using the latest from `develop`? I've never seen this issue on iPhone, but I have seen slow updates after the initial location is sent (and map loaded). Lastly, try turning Wifi off to see if that helps.

**Comment by mecadiego113** [comment] 2017-11-22 17:44
Yes, location is always enabled and the app can use it correctly, but it takes a lot to receive the first location update (the map initialization is delayed a lot then).
Disabling WiFi isn't a valid solution for us: our app uses realtime databases (Firebase) to get and set items, positions, stats, etc. and WiFi is a must. 

Is it possible to call a manual update to location services as we do in the last implementation of Editor `EditorLocationProvider`

**Comment by david-rhodes** [comment] 2017-11-22 17:48
@mecadiego113 Unfortunately, how Unity and iOS handle location services is a bit of a mystery. I've seen some strange behavior with regards to location updates on iOS lately--that's why I suggested you disable Wifi (for testing). My guess is that some combination of Unity/iOS/Device model has some low-level bugs that need to be fixed.

That said, it's also quite possible that my implementation of `DeviceLocationProvider` has some bugs. For example, when the entire sequence was initialized in `Start`, location would not update as often as if it were initialized in `Awake`. Why? I have no idea!

But, feel free to write your own `DeviceLocationProvider` and see if you have better luck.

**Comment by mecadiego113** [comment] 2017-11-22 18:11
Thank you @david-rhodes!

What I just realized is that if I go to Apple's Maps app (or any other app that uses GPS) and then I go back to my Mapbox app, the location is updated and refreshed, and the map initialized as expected...

I have another question about `AbstractMap`: when the `OnInitialize` event is called? At the very first step of initialization or when it's fully initialized (but not fully downloaded -tiles-).

This is a hack, but I could try to perform a map initialization after a short delay just if it isn't initialized yet.
Should `map.Initialize(new Vector3 (Input.location.latitude, Input.location.longitude), map.AbsolutZoom)` work?

Our next internal release is soon, so I can't research for more iOS location issues now, but I will look into this ASAP and post here what I found.

**Comment by david-rhodes** [comment] 2017-11-22 18:40
> What I just realized is that if I go to Apple's Maps app (or any other app that uses GPS) and then I go back to my Mapbox app, the location is updated and refreshed, and the map initialized as expected...

That goes along with my observations. More generally, if you background the app, then foreground again, locations begin to update. This is why I suspect Unity/iOS are at fault. Same location provider works fine on Android, for example.

> I have another question about AbstractMap: when the OnInitialize event is called? At the very first step of initialization or when it's fully initialized (but not fully downloaded -tiles-).

Essentially at the end of `Start` 😉. This means that vital information like `CenterMercator` and `WorldRelativeScale` values have been populated--**NOT** that the map is loaded. For that, you should use the `AbstractMapVisualizer` state event.

> map.Initialize(new Vector2d (Input.location.latitude, Input.location.longitude), map.AbsolutZoom)

I don't know what the goal of this code is. It's essentially what `InitializeMapWithLocationProvider` is doing. But, if you're not getting location events, I suspect this code won't work, either.

**Comment by david-rhodes** [comment] 2017-12-14 17:16
Should be resolved in v1.3, but let's leave this open for posterity for a few weeks.

**Comment by MiroMuse** [comment] 2018-01-03 22:33
@mecadiego113 check out the latest update, and let us know if the issue isn't resolved 👍

**Closed by MiroMuse** 2018-01-03 22:33 UTC
Labels: support
