### ISSUE TITLE
iOS Build Failure - 'MapboxMobileEvents/MapboxMobileEvents.h' file not found

### ISSUE THREAD

**Issue by agent-reed** [mapbox/mapbox-unity-sdk#301] opened 2017-10-18 18:57 UTC
When building from Unity to Xcode. It seems that `MapboxMetricsClient.m` can't import `MapboxMobileEvents.h`

The setup is:
 - Unity 2017.2.0f3
 - Xcode 9.0
 - Multiple Versions of Mapbox-unity-SDK

Using suggestions from other issues (#101 , #247) I've made sure of the following:
 - Deployment Version is set to 8.0
 - Header Search Paths includes: `$(SRCROOT)/Libraries/Mapbox/Core/Plugins/iOS/MapboxMobileEvents/include/`

The strange thing is that the file `MapboxMobileEvents.h` absolutely exists right were the import is looking for it...So it seems like something bizzare with Xcode is going on.  For now, we are able to get by simply by removing `MapboxMetricsClient.m` and any Telemetry Related items in Unity since we don't use any of the Telemetry stuff directly (AFIK). But obviously this isn't what should be done.

Any thoughts?

**Comment by david-rhodes** [comment] 2017-10-18 19:31
We have not been able to reproduce this internally, but so far we have at least three reported resolutions. The gist is: [remove Mapbox SDK from your project and reimport it](https://github.com/mapbox/mapbox-unity-sdk/issues/247#issuecomment-337607714). 

For reference, did you use a .unityPackage to install Mapbox, or our repo? I wonder if this is related to the installation process.

Also, why do you have multiple versions of the SDK?

**Comment by agent-reed** [comment] 2017-10-18 19:34
Sorry, to clarify I meant that we've tried it with multiple versions of the SDK with the same result.

**Comment by UnityEQ** [comment] 2017-10-26 12:33
I had this issue and solved it.

I put the entire mapbox repo inside a child folder in Assets. This is what caused the problem for me.

I took everything out of the child folder, and back into /assets/. This solved the problem for me.

**Comment by david-rhodes** [comment] 2017-10-26 17:03
@UnityEQ Interesting--thank you for the find! I don't think we've ever tested that, but it makes perfect sense to allow developers to nest plugins as they see fit. I'll create a ticket to track that.

**Comment by david-rhodes** [comment] 2017-10-26 20:44
Closing in favor of #327

**Closed by david-rhodes** 2017-10-26 20:44 UTC
Labels: support

**Comment by apavani** [comment] 2017-11-27 19:47
I discovered that this error occured for me because I had the Symlink Unity Libraries checkbox turned on while building for iOS.
Please make sure this is unchecked before building
![33154796-e62110da-cf9f-11e7-8010-c7e488e81b6b](https://user-images.githubusercontent.com/8422708/33285966-cecef1e6-d368-11e7-875f-f2d6546c920f.png)

**Comment by retinize** [comment] 2018-07-23 16:11
Was there ever a fix for this? I have ensured Symlink Unity Libraries is unchecked as above. Also moved the full MapBox directory to a child folder and back to original directory as advised but neither worked for me.

**Comment by kaitlynhwang** [comment] 2018-10-17 23:40
Just got this problem when building for Ios. You can take the code/example from https://www.mapbox.com/help-video/tutorials/unity-game-pocketdroids-go/ 

Xcode Version 10.1 beta (10O23u)
Unity 2018.2.10f1
mapbox-unity-sdk_v2.0.0.unitypackage

**Comment by dpruitt90** [comment] 2018-10-30 21:19
Same problem.  Taking project source from an online course and attempting to run it on iPhone and I receive this error.  I just upgraded to the latest version of unity.  Is there a fix for this?  Using the Mapbox ARTable Top with modifications for Drenches of War class on UDemy.

**Comment by vl4dimir** [comment] 2018-10-31 11:38
Same problem here. From [official Unity docs](https://docs.unity3d.com/Manual/PluginsForIOS.html):

> Note: Subfolders are currently not supported.

Could this be the culprit?

**Comment by vl4dimir** [comment] 2018-10-31 11:51
Confirmed fix:

1. Move all files from `Assets/Mapbox/Core/Plugins/iOS/MapboxMobileEvents/include/` and `Assets/Mapbox/Core/Plugins/iOS/MapboxMobileEvents/` directly into `Assets/Mapbox/Core/Plugins/iOS/`
2. Build the project.
3. Change all `#import`s that are throwing errors from the `#import <MapboxMobileEvents/MapboxMobileEvents.h>` format to the `#import "MapboxMobileEvents.h"` format.

@atripathi-mb I tried your approach but I got the same errors. This seems to be related to subfolders not being supported.

**Comment by vl4dimir** [comment] 2018-10-31 12:33
OK this is how I finally got the Xcode build to work:

1. Build the project from Unity.
2. In Xcode, add `$(SRCROOT)/Libraries/MapBox/Core/Plugins/iOS/MapboxMobileEvents/include` to `Header Search Paths`.
3. In Build Phases → Link Binary With Libraries, click the "+" sign and add `libz.tbd`
4. Build and run.

Hope this helps the maintainers nail down the cause of the issue! 😎

**Comment by mhellnerdev** [comment] 2019-07-06 07:09
> Another possible solution/workaround is here: #1353

This is the solution here.  Fixed my issue.  I'm working on PC and pushing through git to my mac to build.  thank you!

**Comment by oliviajohansen** [comment] 2021-01-03 07:18
For me the problem was because the imported file path did not correspond to the actual location of the file. How I got it to work was: 
1. Inside MapboxMetrics.Client.m change the import line 1 from ```#import <MapboxMobileEvents/MapboxMobileEvents.h>```
 to ```#import "MapboxMobileEvents/include/MapboxMobileEvents/MapboxMobileEvents.h"```
2. Inside MapboxMobileEvents.h change the import lines 11-14 from 
```
#import <MapboxMobileEvents/MMEConstants.h>
#import <MapboxMobileEvents/MMEEvent.h>
#import <MapboxMobileEvents/MMETypes.h>
#import <MapboxMobileEvents/MMEEventsManager.h>
```
to 
```
#import <MMEConstants.h>
#import <MMEEvent.h>
#import <MMETypes.h>
#import <MMEEventsManager.h>
```

**Comment by olgv** [comment] 2021-02-07 13:20
The above worked for me, BUT 
...in conjunction [with this thread](https://github.com/mapbox/mapbox-unity-sdk/issues/1353) related to the `Build` folder being lost due to `.gitignore`

**Comment by bryanrtboy** [comment] 2022-02-16 22:31
What finally worked for me was to select the UnityFramework in XCode, and then add this entry to the Header Search Paths - "$(SRCROOT)/Libraries/Mapbox/Core/Plugins/iOS/MapboxMobileEvents/include"

I found this by cloning the mapbox-unity-sdk project (which built fine) to a new project where I imported the .package file from map-box. Literally every setting, library, dependency was identical except for the above.

**Comment by romtecmax** [comment] 2023-08-28 13:40
this issue persists as of August 2023 and the solutions in this thread were of no use so far. it is frustrating because it prevents me from using mapbox at all in my project. If anyone has a newer working solution let me know!
