### ISSUE TITLE
Failure to read custom style

### ISSUE THREAD

**Issue by derekdominoes** [mapbox/mapbox-unity-sdk#87] opened 2017-05-24 14:31 UTC
Import a shp file based Dataset into Mapbox Studio. 
Made a Tileset out of it.
Added the Tileset vector layer to a new Style
Published the Style
Added Style URL to 
Updated access token in Unity project
In TerrainDemoMeshFactory inspector:
    Added style MapId uri to TerrainDemoMeshFactory
    Added key for my data to DriveBuildingVisualizer
Debugged this Unity project
VectorTileReader.cs:52 throws exceception "Unknown tile tag: 15"
I just want to see if I can get the data over. Then I will build my own visualizer. It reads something, but apparently this isn't a Layer

**Comment by BergWerkGIS** [comment] 2017-05-24 14:36
@derekdominoes Could you double check the access token?

**Comment by derekdominoes** [comment] 2017-05-24 14:42
Yes, It is taken from the "Develop with the style" section and validated in the Unity Editor when I added it from the menu.

**Comment by BergWerkGIS** [comment] 2017-05-24 14:46
@derekdominoes are you still using 0.4 of the SDK?
We had a bug when a requested tile did not exist that could cause that error, but that should be fixed with current versions.
Either unitypackage 0.5.1 or `develop` branch directly from here.

**Comment by derekdominoes** [comment] 2017-05-24 14:59
v0.5.1-beta
I'll help you debug any way I can?

**Comment by derekdominoes** [comment] 2017-05-24 15:03
Here is the request going across if it helps:
https://api.mapbox.com:443/v4/mapbox:/styles/taitex/cj332db8u00342smdjnu9akqc/14/3401/6200.vector.pbf?access_token=pk.eyJ1IjoidGFpdGV4IiwiYSI6ImNqMnI4NzdjbzAwNjMzM3E4ZDJ1ZGJleHEifQ.W1msqGd3DHBUVx7HHzFS7Q

**Comment by BergWerkGIS** [comment] 2017-05-24 15:10
@derekdominoes thanks for the request.
The problem is as expected, if you open the URL in a browser you get `Not Found`.
So the response should never get to `VectorTileReader`.
I thought the fix was already in 0.5.1

Let me check the code ...

**Comment by david-rhodes** [comment] 2017-05-24 15:11
@derekdominoes I'm a bit confused. Are you trying to render the custom tileset in a raster tile, or extract raw data from the vector tile generated from your tileset? It sounds like you are trying to use a style URL for the mesh factory, and that will not work.

If you are trying to use vector tiles,  the layer name is the name of the tileset and the `MapId` should start with your mapbox studio username.

If you want to use raster tiles, then you need to put your style url in the `MapImageFactory`, instead.

**Comment by derekdominoes** [comment] 2017-05-24 15:37
I didn't open it in a browser. I just grabbed the path out of the HTTPRequest.cs so you may be able to try it. It is returned a byte[] that is given to VectorTileReader.
I don't doubt I don't have it configured correctly. I only put things in the only places I could find proper fields for as I can't find documentation on this whole process and how to configure the components in the Unity Inspector.
I have vector data from a shp file I want to see in my Unity app using the MapBox  Unity SDK. I've imported it into MapBox Studio. It seems the only way to get it delivered to me is to add it to a Style and publish the style. Inside the TerrainDemoMeshFactory in the inspector, I am added the uri starting with "MapBox:/styles..." that I got from MapBox Studio. The "key" for the visualizer is the name of the tileset.
At your suggestion, I removed the everything before my username from the MapId so that it is sending: https://api.mapbox.com:443/v4/taitex/cj332db8u00342smdjnu9akqc/14/3401/6200.vector.pbf?access_token=pk.eyJ1IjoidGFpdGV4IiwiYSI6ImNqMnI4NzdjbzAwNjMzM3E4ZDJ1ZGJleHEifQ.W1msqGd3DHBUVx7HHzFS7Q  but the error still occurs.

**Comment by david-rhodes** [comment] 2017-05-24 15:59
@derekdominoes Do you want images or raw data for your visualization? If you want raw data, you cannot use a style url--you need to get the `Map Id` from the tileset itself (it does not need to live in a style). You can find this in the tileset editor in Mapbox Studio.

If you want images, paste that style url into the image factory--not the mesh factory! Your URL should look like this:  https://api.mapbox.com/styles/v1/taitex/cj332db8u00342smdjnu9akqc/tiles/14/3401/6200?access_token=pk.eyJ1IjoidGFpdGV4IiwiYSI6ImNqMnI4NzdjbzAwNjMzM3E4ZDJ1ZGJleHEifQ.W1msqGd3DHBUVx7HHzFS7Q.

I recommend you scrub your personal token and get a new one so nobody steals this.

**Comment by derekdominoes** [comment] 2017-05-25 09:39
Thank you David. I was able to get it working by creating a MeshFactory with my MapId from the TileSet and it has a Visualizer with my TileSet's Keyname. I can now see the polygon from the imported shape file along with properties from the shapes.
I even have GameObjectModifier working. 
Nice architecture!

**Comment by david-rhodes** [comment] 2017-05-25 14:41
@derekdominoes Glad it worked for you!

**Closed by david-rhodes** 2017-05-25 14:41 UTC

**Comment by richabwt** [comment] 2018-03-29 12:26
hey is there anybody to help i am getting little confused in integrating mapbox-unity-sdk_v1.4.0 in unity 2017.3.1f1 as i know  mapbox-unity-sdk_v1.4.0  is the latest version but i can't find vector tile factory in mapbox and also maptype in image factory of mapbox so please let me know is these option is removed from the latest version

**Comment by atripathi-mb** [comment] 2018-03-30 06:47
@richabwt vectortilefactory is setup using the `Vector` section under AbstractMap inspector. Maptype is now `Style Name` under `Image` section

**Comment by richabwt** [comment] 2018-03-30 07:00
@atripathi-mb Thanku for your answer i find it but i am trying to achieve features like this link
http://www.yudiz.com/design-your-map-in-mapbox-and-integrate-it-in-unity-part-1/?fb_comment_id=1336749689769250_1525624974215053#f186effe5f68518

but i think this tutorial follow the older version of mapbox so please let me know is there any updated tutorial or link to do it.

**Comment by richabwt** [comment] 2018-03-30 07:15
@atripathi-mb  Thanku for your reply i find it but i didn't find any integration link of latest version mapbox sdk in unity please help me out.
