### ISSUE TITLE
Reload Map on Zoom - Globe Example

### ISSUE THREAD

**Issue by phgold** [mapbox/mapbox-unity-sdk#884] opened 2018-06-26 18:18 UTC
Hello.
I'm relatively new to the Unity universe, and I just learned about mapbox today.
I have been fidling with it for some hours.
I'm trying to build a Globe map that updates as you zoom in, just as google maps or earth, for an Android Device.
I can't wrap my head around as how to make it work, since the ZoomableMap example is a 2D map. 

Any Ideas on how to implement this feature in the Globe example?

Using Unity 2018.1.3
MapBox SDK 1.4.3.

**Comment by jordy-isaac** [comment] 2018-07-02 17:02
Closing this one as it's a duplicate of: https://github.com/mapbox/mapbox-unity-sdk/issues/892

**Closed by jordy-isaac** 2018-07-02 17:02 UTC
Labels: support
