### ISSUE TITLE
Unity Editor crash  when the example is played

### ISSUE THREAD

**Issue by markl93** [mapbox/mapbox-unity-sdk#160] opened 2017-07-14 13:56 UTC
When i open example MeshGenerationBasics and set zoom to 18, and coordinates set to 42.3605, -71.0596 editor crashed. If i turn off buildings - it's ok.

All other settings is standart.

**Comment by brnkhy** [comment] 2017-07-14 14:09
Hey @markl93, two questions to begin with;
-What's the version of Unity Editor you're using?
-Are you using the latest from repo or the 1.0 release package? (if you're using the package, can you try with the latest from repo again?)

**Comment by markl93** [comment] 2017-07-14 14:14
Hi @brnkhy. Unity version is 2017.1.0b10 and i using package 1.0 .
I'll try with repo.

**Comment by brnkhy** [comment] 2017-07-14 16:13
@markl93 `But repo examples is broken (develop branch)` broken? how? are you getting error messages or something?

**Comment by david-rhodes** [comment] 2017-07-19 22:22
@markl93 Any updates here? We cannot reproduce on our end. Does this still occur?

**Comment by markl93** [comment] 2017-07-20 08:12
@david-rhodes I try on release version 2017.1 and same problem. And I couldn't start example from git version of sdk. Maybe I couldn't add correctly dependencies.

I think, maybe my mac mini so slow to open that amount of buildings in one scene..

**Comment by david-rhodes** [comment] 2017-07-20 14:51
How many tiles are you requesting @markl93? Are all the example broken for you? How much memory does your computer have?

**Comment by BergWerkGIS** [comment] 2017-07-27 09:44
> But repo examples is broken (develop branch)

@markl93 did you run [`update-mapbox-unity-sdk-core.bat`](https://github.com/mapbox/mapbox-unity-sdk/blob/develop/update-mapbox-unity-sdk-core.bat) or [`update-mapbox-unity-sdk-core.sh`](https://github.com/mapbox/mapbox-unity-sdk/blob/develop/update-mapbox-unity-sdk-core.sh) (depending on the OS you are on) after pulling the repo?

**Comment by david-rhodes** [comment] 2017-08-04 02:17
@markl93 closing for now, please let us know if you still have issues.

**Closed by david-rhodes** 2017-08-04 02:17 UTC
