### ISSUE TITLE
Support trouble with FPS map

### ISSUE THREAD

**Issue by ejgutierrez74** [mapbox/mapbox-unity-sdk#1152] opened 2018-12-04 09:46 UTC
Hello, im working in my Master Final Thesis in computer science flavoured in VideoGames.

My idea was to get from a mapbox one 3d map about 1km2 from my city ( LLeida, Spain: 41.612974, 0.623518) and use it to develop a FPS where my player could move around the different streets and places. The objective would be to discover some boxes with clues and following the clues discover the final place and arrive to it.

So i dont really need realtime information or connection ( once i have the map). Also would prefer to download it ( faster loading). I also need a 3d map with buildings and player be at floor level. Buildings should be colliders to avoid pass through them.

I think this purpose can be done with mapbox, but i cant get with it. Seems that the tutorial is a little outdated because i dont have the vector settings( i use https://www.mapbox.com/help/create-a-map-in-unity/ trying to get a similar manhattan downtown).

So my questions are:
 1 - Is my idea possible using mapbox ? Can i put a player at floor-level something like google street view using buildings and 3d ?
2 - I have to import the mapbox unity custom package in every project i use it ? Is it safe to delete all the assets and examples imported ?
3 - I want to download a zone of the map and use it as a game map, dont need geolocalization of the player as it wont be a AR or VR project.... Is this possible ?
4 - I attach my tests following the tutorial but i cant get to work...if anybody could take a look would be great. 

https://drive.google.com/open?id=1MTFCNhMT53xVxIuIbAvg1ZJQyMnymFpr

Thanks in advance, and congrats for your great sdk

The main questions is its possible with mapbox ? If so what kind of example/sample project should i use to begin ( there are so different templates and different maps ) ?
- version: 2.0.0 Unity Version: Linux Editor 2017.4.14f1

**Comment by jordy-isaac** [comment] 2018-12-05 17:59
@ejgutierrez74 It looks like you have a duplicate of this ticket open with the support team. We'll get back to you on that thread.

**Closed by jordy-isaac** 2018-12-05 17:59 UTC

**Comment by ejgutierrez74** [comment] 2018-12-06 11:30
Sorry i thought the mail with support team didnt work.....
