### ISSUE TITLE
Curl error 61 in editor with certain map features

### ISSUE THREAD

**Issue by KuraiAndras** [mapbox/mapbox-unity-sdk#1778] opened 2021-05-06 13:41 UTC
* Unity version: 2021.1.3+
  * Scripting Runtime Version: Default
  * Scripting Backend: IL2CPP
  * Api Compatibility Level: .NET Standard 2.0
* Mapbox SDK version: 2.1.1
* The platform you're building to: Editor
* A description of what you're trying to do:
  * Use additional map features, POI, or 3D buildings
* Steps to recreate the bug if appropriate:
  * Try any sample scene in the editor which uses the mentioned map features
* Links to your logs are also helpful: 
![image](https://user-images.githubusercontent.com/19240945/117306424-f9cd6800-ae7f-11eb-9c63-0147db677015.png)

The error only occurs in the editor when using Unity versions newer than 2021.1.2. Curiously the error does not happen in build (WebGL). According the [release notes of 2021.1.3](https://unity3d.com/unity/whats-new/2021.1.3) Unity updated UnityWebRequest's libCurl backend. After the update Microsoft Play Fab also experienced a [similar issue](https://community.playfab.com/questions/51765/libcurl-bug-in-unity-202113f1.html?page=1&pageSize=10&sort=oldest).

I would try to fix this manually, but the error does not contain any stacktraces.

**Comment by janweigel** [comment] 2021-06-01 12:00
Some problem here on Unity 2020.3.9
Curl error 61: Unrecognized content encoding type. libcurl understands identity content encodings.

No stack trace or anything else.
Mapbox does not load new tile data.

Any help appreciated

**Comment by MRKDaGods** [comment] 2021-06-01 17:33
The issue arised since Unity 2020.2 I guess, it is due to an updated version of Curl not supporting whatever header value of 'Content-Encoding' is set to. I suggest that you debug the headers received from the WebRequest

**Comment by MRKDaGods** [comment] 2021-06-01 17:35
@brnkhy Please take a look at this

**Comment by KuraiAndras** [comment] 2021-06-14 15:32
Any update on this?

**Comment by janweigel** [comment] 2021-06-19 14:58
The Problem still exists in Untity 2020.3.12
It's not possible to get new tiles without error in Editor.
Could someone please take a look at this?
Thanks

**Comment by mniebieski** [comment] 2021-07-06 07:35
Thx

Wow, so the issue is almost 3 years old and they didnt update the SDK? If that's how Mapbox approaches all their products, then I'm not inpressed.

**Comment by brnkhy** [comment] 2021-07-07 08:46
Hey everyone, 
I finally had a chance to look into this. Problem is Unity editor is just dropping gzip packages automatically in certain versions (2020.3+ I think) and Mapbox servers are strictly `gzip-only`.
I'm looking for a workaround but there probably will not be one.
I found this on the other hand; https://issuetracker.unity3d.com/issues/unitywebrequest-fails-on-windows-if-gzip-compression-is-used

Information is very vague on that page but it claims fix is
```
Fixed in 2022.1.X
Fix In Review for 2019.4.X
Planned for 2020.3.X, 2021.1.X
```
So looks like Unity recognizes this as an issue/bug and it'll be fixed.

**Comment by Markovicho** [comment] 2021-08-02 07:50
I can confirm that this bug is not present until 2020.3.7f but seems to appear a few versions later based on the libcurl upgrade. So stick with this version to get rid of this issue combined with 2020.3 LTS .
I will keep an eye on the changelog for 2020.3.x and leave an comment when the fix is integrated. It's a bit strange that the issuetracker is marking 2020.3.x as fixed which is definately not the case yet.

**Comment by gisinator** [comment] 2021-08-13 14:49
This has been fixed in 2020.3.16f1. Unity editor now supports gzip and I can confirm that this error is gone.

**Comment by KuraiAndras** [comment] 2021-08-13 15:09
2021.1.16f1 is still bad :(

**Comment by Markovicho** [comment] 2021-08-13 15:42
@gisinator thx for the information. will check out the new version as soon as possible !
@KuraiAndras is the fix listed in the changelog for 2021.1.16f1 ? What features are you using which are not included in 2020 LTS ?

**Comment by KuraiAndras** [comment] 2021-08-13 16:16
To be honest not much. The thing is that we constantly keep our projects up to date with the latest Unity versions, to avoid the hassle when updating major versions. So far it have served us fine.

**Comment by Markovicho** [comment] 2021-08-13 16:25
It's a matter of taste. We are jumping also as early as possible to avoid large gaps between the versions. But for my taste stable to stable seems bit more reliable. 
Is everything else working fine regarding mapbox ?

**Comment by KuraiAndras** [comment] 2021-08-13 17:17
Well everything else is fine. We did have to do a few modifications to the source code to have better performance in WebGL but other than that it worked quite well.

**Comment by KuraiAndras** [comment] 2021-08-19 11:04
The fix landed in 2021.1.17, the editor works as expected 🎉

**Comment by brnkhy** [comment] 2021-08-19 11:53
@KuraiAndras awesome, thanks for letting us know!

2020.3.16f1
2021.1.17
seems good for now 👍

**Comment by mingyu0403** [comment] 2021-08-20 00:49
I'm having the same problem. Unity 2021.1.15f1 Version. URP Project.
'Curl error 61: Unrecognized content encoding type. libcurl understands identity content encodings.'

how to fix it?? just version upgrade??
I will be glad for your help.

**Comment by mingyu0403** [comment] 2021-08-20 02:35
it works fine in (Unity 2021.1.17f1, Unity 2020.3.16f1) 
regardless of URP.
oh yeeeeah!!

**Closed as completed** 2022-09-11 08:24 UTC
