### ISSUE TITLE
WorldRelativeScale only changes on whole numbers

### ISSUE THREAD

**Issue by jonathan84clark** [mapbox/mapbox-unity-sdk#1374] opened 2019-05-23 16:26 UTC
* Unity version: 2018.3.14f1
  * Scripting Runtime Version: Visual Studio 2017 15.9.6
* Mapbox SDK version: 2.0.0
* The platform you're building to: Windows

I have created a set of points in my application with a line renderer connecting them.
Each point object is supposed to maintain its relative position at any zoom level and any map position.
This is done by calling the following function each Update
`            Vector3 newUnityPosition = Conversions.GeoToWorldPosition(geoPosition, map.CenterMercator, map.WorldRelativeScale).ToVector3xz();
            newUnityPosition.y = height;
            unityPosition = newUnityPosition;`

**Condition that works**
When I maintain a zoom level that is a whole number (i.e, 9, 10, 11, 12, 13) then I move the map around (by changing the center mercator)  like so:
`                float factor = _panSpeed * Conversions.GetTileScaleInDegrees((float)map.CenterLatitudeLongitude.x, map.AbsoluteZoom) / map.UnityTileSize;
                var latitudeLongitude = new Vector2d(map.CenterLatitudeLongitude.x + ySlide * factor, map.CenterLatitudeLongitude.y + xSlide * factor);
                map.UpdateMap(latitudeLongitude, map.Zoom);`

The points and therefore the line maintain a fixed relative position on the map

**Condition that fails**
However when I zoom to a non-whole number the Unity position is not correct and the points and line appear to drift.

**What I know so far**
I believe that the issue is related to the WorldRelativeScale value of the Abstract map object. It only changes when the zoom level reaches a whole number. Since the geoposition is a fixed point and the CenterMercator doesn't get changed when zooming the only possible issue is that the third variable; the scale is not changing and therefore the calculation always returns the same value.
Is it possible this is by design? Or is there a rounding issue somewhere in the MapBox Unity SDK?
I am going to continue to dig through the Mapbox SDK code to see if I can find anything else.
Any help from you on this would be great!

Thanks,

Jonathan L Clark

**Comment by jonathan84clark** [comment] 2019-05-23 17:27
Okay I found a solution/workaround. I simply need to adjust the WorldRelativeScale by some decimal factor and compute my own WorldRelativeScale because the WorldRelativeScale appears to only change when tilesets get changed that's why I am seeing this. So my question is answered; this is by design.
Here is the solution:
`            int wholeVal = (int)map.Zoom;
            float unwholeScaleFactor = (map.Zoom - wholeVal) * map.WorldRelativeScale + map.WorldRelativeScale;
            Vector3 newUnityPosition = Conversions.GeoToWorldPosition(geoPosition, map.CenterMercator, unwholeScaleFactor).ToVector3xz();
            Vector3 newUnityPosition = Conversions.GeoToWorldPosition(geoPosition, centerMarcator, mapZoomScale).ToVector3xz();
            newUnityPosition.y = height;
            unityPosition = newUnityPosition;`

**Comment by brnkhy** [comment] 2019-05-27 15:54
@jonathan84clark I think you're using a map based on (or similar to) ZoomableMap demo scene? I think this would be expected then as Zoomable map scales map objects in between zoom levels and only triggers changes on whole number changes as you noted. 
Still, I think it might not break it if it updates `WorldRelativeScale` either but since it's not used during that range, we probably looked over it as it wasn't necessary.
Great catch though, I think I understand it and I'll try to test&see it myself.
I'm closing this for now as it looks like you found a workaround.
Thanks a lot!

**Closed by brnkhy** 2019-05-27 15:54 UTC

**Comment by syameshk** [comment] 2019-10-10 07:50
I noticed that the solution/workaround also has some error(small but exists) in it. I think map box should fix this issue. Like, if you call it 'WorldRelativeScale' it has to be relative. @brnkhy

**Comment by halzate93** [comment] 2020-03-21 02:05
I struggled with this as well, working on top of the zoom examples. I realized that the WorldRelativeScale is correct as it was designed for integer zoom levels. Then the AbstractMap has some code to apply a localScale on top of that based on the floating point difference and adjusts for it in between. This is the code that helped me keep a radius boundary with consistent size regardless of zoom level:

```cs
private void Update () 
    {
        //Debug.Log("Setting playerRadius from " + PlayerRadius.transform.localScale.x + " scale by " + (1/scaleFactor));
        RectD referenceTileRect = Conversions.TileBounds(TileCover.CoordinateToTileId(_map.CenterLatitudeLongitude, _map.AbsoluteZoom));
        double differenceInZoom = _map.Zoom - _map.InitialZoom;
        double unitsPerMeter = _map.Options.scalingOptions.unityTileSize / referenceTileRect.Size.x;
        double localScale = (double)_initialScale * (double)radiusMeters * 2d * unitsPerMeter * Mathd.Pow(2d, differenceInZoom);
        transform.localScale = Vector3.one * ((float) localScale);
	}
```
