### ISSUE TITLE
VectorTileFactory doesn't trigger `Finished` state for zoom levels with no data

### ISSUE THREAD

**Issue by atripathi-mb** [mapbox/mapbox-unity-sdk#505] opened 2018-01-16 22:27 UTC
The `Loading` message keeps blinking on the screen even after the content is loaded in the background.
The issue occurs if there is Vector data in scene & zoom level is less than 10 ( zoom level at which the vector data is not available)

Factory state is never set to Finished.

To reproduce 
1. Open Basic Vector Map example. 
2. Change zoom to 6
3. Press play - loading screen will keep displaying infinitely .

**Comment by BergWerkGIS** [comment] 2018-01-17 07:43
Able to reproduce with above instructions.

**Comment by brnkhy** [comment] 2018-01-17 09:45
I was able to reproduce as well, thanks for the ticket @atripathi-mb.

This is an annoying bug. I was able to fix it with a simple change to an if clause really but looking for improvements and/or better solution at the moment.

Problem is that when VectorFactory doesn't do anything at all (no layer visualizers matching data layers, so you can have same issue at zoom16 and just water layer visualizer in the middle of land space), it just waits in `Initialized` state while MapVisualizer expects it to switch to `Finished` eventually.

Possible solutions might be, (1) accepting `Initialized` state as something like "waiting for work" or (2) maybe even create another state like that. Thinking about it, `Finished` also means "waiting for work" right? So these enums might be semantically wrong all together. 
(3)Maybe we can just have two states; `working` means some coroutines inside is not finished and `waiting` for the opposite.
I'm not sure about having just two states though. Maybe we can have multiple and just group them (not by code) into those two working/waiting. i.e. Initialized and Finished would be "waiting" so all if clauses can work like that. But that's actually same as the option (1) and the snippet below also works like that.

Quick fix is to change AbstractMapVisualizer.cs Line 152;
from;
```
if (Factories[i] != null)
{
	allFinished &= Factories[i].State == ModuleState.Finished;
}
```

to
```
if (Factories[i] != null)
{
	allFinished &= Factories[i].State == ModuleState.Finished || Factories[i].State == ModuleState.Initialized;
}
```

**Comment by atripathi-mb** [comment] 2018-01-18 06:13
@brnkhy 
When I was tracking down the issue, my understanding was that the issue is here 
https://github.com/mapbox/mapbox-unity-sdk/blob/7e436328da40252e6af517cc9c196e88282e1462/sdkproject/Assets/Mapbox/Unity/MeshGeneration/Factories/VectorTileFactory.cs#L186

The progress counter triggers the state change, but this loop is not triggered when there is no data to process? Would updating the state to finished even when no work needs to be done be enough to fix the issue?

**Comment by brnkhy** [comment] 2018-01-18 09:09
@atripathi-mb I also tried setting state to finished by default or changing it to "finished" after initialization but had other problems. For example it worked visually but I noticed too many wrong state switches at the background like this;
![unity_2018-01-18_11-52-22](https://user-images.githubusercontent.com/1465390/35088838-106f8326-fc46-11e7-98e4-5da1b0ea71f5.png)
I'm not exactly sure why this is happening but my guess is now that vector tile factory is finished, terrain and image factories probably ends instantly for each tile and we're getting "finished" after each tile. 
We actually have a one frame delay in vector tile factory to prevent it finishing in same frame but I can't remember adding that to others as well.

As I said I like feel those enum names are a little confusing. Also it might be really nice to change how we process tiles in factory. We're currently getting tile requests one by one and that's causing most of these issues. If we calculate all required tiles in that frame and pass it as a list, I feel like most of these problems would become much easier to solve.

**Comment by brnkhy** [comment] 2018-02-20 12:45
just taking notes 
- I'm rethinking some core concepts about this. I feel like "map is finished" and "systems are done" aren't necessarily same thing for example. Especially when we begin implementing update cycles (we probably will) to modules.
At the moment, Map visualizer is throwing even based on factory state. If factories are done, we're throwing map loaded event but that isn't necessarily correct of course. Especially if we ever want to do something like distributed mesh generation where each independant feature script calculates its own stuff etc (we might d something like that with jobs system). So I believe factories shouldn't be the criteria here because they might finish before features are actually finalized or keep working even after all features are done.

Maybe a better approach would be; map is done when all tiles are done and a tile is done when terrain, imagery and all features are loaded&finished.
MapVisualizer keeps track of tile so it can easily check them whenever necessary. We don't have a state indicator or anything in tiles though (talking about UnityTile here). Tile keep terrain and imagery data so we can probably check if they are loaded easily but data being loaded doesn't mean terrain mesh generation is finished for example. That doesn't work with vector data either because we want to distribute that over bunch of frames after data is loaded as well.

So let's say we implemented two changes we've been talking for so long; rewoking modifier stacks (to make them stronger and focused) and pass features down the tree as list instead of one-by-one. Then modifier stacks can probably keep track of features easier as they control them all anyway. Update Tile object about their state and then we can check if a tile is finished or not from UnityTile script.
One problem I have with this is adding yet another thing into UnityTile class which is kinda unorganized already.

**Comment by brnkhy** [comment] 2018-02-21 11:40
@atripathi-mb what do you think about this? Current implementation isn't enough anymore and even though we can patch it, it's still kinda ugly solution. I believe we can find something better but it would take quite some change. Maybe we can do such a change with our current changes?

**Comment by atripathi-mb** [comment] 2018-02-22 06:03
@brnkhy 
>what do you think about this? Current implementation isn't enough anymore and even though we can patch it, it's still kinda ugly solution. I believe we can find something better but it would take quite some change. Maybe we can do such a change with our current changes?

I agree with your suggestions. Having states for tile status & moving the responsibility to modifiers is going to give us more benefits in the long term. Lets discuss possible solutions and go from there.

**Comment by demi180** [comment] 2018-03-07 21:12
@brnkhy if you guys are reworking the stacks, I suggest adding an way to run (an)other operation(s) after the per-feature modifiers have all completed (but before the completion callback gets called), like you did with the MergedModifierStack's End() function.

Ex: I'm working on a "post-merged stack" right now that does basically what the merged stack does, but uses the already-built objects in order to keep the collision info in place. But it could be useful to be able to just plug in a separate behavior for that instead of deriving from the stack itself.

Food for thought :)

**Comment by brnkhy** [comment] 2018-03-07 21:17
@demi180 that sounds good, no reason not to have it on regular modifier stack either I guess. Maybe even make it modular if we can think of multiple usecases as well. Or might be a simple event/unityevent maybe?
Thanks for the feedback!

**Comment by MiroMuse** [comment] 2018-03-29 16:18
Closing in favor of: https://github.com/mapbox/mapbox-unity-sdk/issues/624

**Closed by MiroMuse** 2018-03-29 16:18 UTC
Labels: bug, enhancement
