### ISSUE TITLE
NullReferenceException on a Singleton.instance

### ISSUE THREAD

**Issue by mayo-cross** [mapbox/mapbox-unity-sdk#116] opened 2017-06-08 18:31 UTC
We are getting an weird exception when; after loading the map, we go to another scene, and then we go back to the map scene.

``` 
NullReferenceException
I/Unity   (12213):   at UnityEngine.MonoBehaviour.StartCoroutine (IEnumerator routine) [0x0000e] in /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/MonoBehaviourBindings.gen.cs:63
I/Unity   (12213):   at Mapbox.Unity.Utilities.Runnable+Routine..ctor (IEnumerator a_enumerator) [0x00015] in /.../Assets/Plugins/Mapbox/Core/Unity/Utilities/Runnable.cs:115
I/Unity   (12213):   at Mapbox.Unity.Utilities.Runnable.Run (IEnumerator routine) [0x00002] in /.../Assets/Plugins/Mapbox/Core/Unity/Utilities/Runnable.cs:47
I/Unity   (12213):   at Mapbox.Unity.Utilities.HTTPRequest..ctor (System.String url, System.Action`1 callback) [0x00020] in /.../Assets/Plugins/Mapbox/Core/Unity/Utilities/HTTPRequest.cs:34
I/Unity   (12213):   at Mapbox.Unity.MapboxAccess.Request (System.String url, System.Action`1 callback) [0x00069] in /.../Assets/Plugins/Mapbox/Core/Unity/MapboxAccess.cs:121
```

We are getting a `Singleton.instance == null`, specifically in [Runnable.cs Line 116](https://github.com/mapbox/mapbox-unity-sdk/blob/7f9d203e38c9bbf205c6433bf9de08b8ed9b6a7b/sdkproject/Assets/Mapbox/Unity/Utilities/Runnable.cs#L116)

It's a little bit weird because is not happening in the editor (only in devices) unless you activate/uncomment the `#define SINGLETONS_VISIBLE` line.

Seems like the cause of the issue is in your: 
[Singleton.cs Line 44](https://github.com/mapbox/mapbox-unity-sdk/blob/7f9d203e38c9bbf205c6433bf9de08b8ed9b6a7b/sdkproject/Assets/Mapbox/Unity/Utilities/Singleton.cs#L44)

The first time the null comparison will work, but if the monobehaviour/singleton_instance is destroyed,  `sm_Instance == null` it will not.

Unity thinks that this specific variable (`Runnable : Monobehaviour` )  is not null so doesn't call `CreateInstance();`

I think that it is related with a Unity custom == operator and destroyed objects.
References: 
[https://forum.unity3d.com/threads/null-check-inconsistency-c.220649/#post-1775701](https://forum.unity3d.com/threads/null-check-inconsistency-c.220649/#post-1775701) and: 
[https://blogs.unity3d.com/2014/05/16/custom-operator-should-we-keep-it/](https://blogs.unity3d.com/2014/05/16/custom-operator-should-we-keep-it/)

and a possible solution it could be use this

`if (EqualityComparer<T>.Default.Equals(sm_Instance, null))`

instead of 

`if (sm_Instance == null)` 

int your Singleton file.

**Comment by binakot** [comment] 2017-06-08 19:16
May be this is concurrency problem? There is no lock or smth else. Scripts work from different threads. Probably singleton reference should be volatile? I already gave this link in another issue #46. Do this again http://wiki.unity3d.com/index.php?title=Singleton

**Comment by mayo-cross** [comment] 2017-06-08 20:29
Locking doesn't fix the problem. Which is still the `null` validation.

**Comment by binakot** [comment] 2017-06-10 09:30
@mayo-cross Hmm, I can suggest only to re-write singleton implementation, while it fixed up. Than contribute solution here ;) Or waiting for developer's answer. Cheers!

**Comment by mayo-cross** [comment] 2017-06-12 15:44
Yep, that is what I did, the `possible solution` is what I am using. I guess that I can make a pull request with that.

**Comment by david-rhodes** [comment] 2017-06-16 16:01
@mayo-cross Thanks for the report! I've been on vacation, but we'll take a look soon. In the meantime, we do value pull requests! 👍 

Also, this is very interesting:
> I think that it is related with a Unity custom == operator and destroyed objects.

Thanks for the information!

**Comment by david-rhodes** [comment] 2017-07-11 20:46
@mayo-cross Just now coming around to this issue. I am unable to reproduce this error in iOS or the editor, with or w/o `#define SINGLETONS_VISIBLE`.

What's interesting, however, is that the first time I load a map, I see a `_Runnable` game object in the scene. For every scene thereafter, I see no runnable components, but the `Runnable` is still executing coroutines as expected.

I'm curious, are you manually destroying any objects or just loading new scenes (non-additively)? [The Unity docs](https://docs.unity3d.com/ScriptReference/HideFlags.DontSave.html) claim that the game object will not be destroyed when changing scenes, due to the `HideFlags`.

Other notes:
- `CreateInstance()` in `Singleton` is only being called once.
- Check out my test project here: https://github.com/mapbox/mapbox-unity-sdk/tree/scene-change-test
- Tested with Unity 5.4.3 (perhaps this is a bug in newer versions?)

**Comment by mayo-cross** [comment] 2017-07-12 19:32
Hi @david-rhodes !
We were using Unity `5.6.0f3`,  and we experienced the error on an Android device but I don't remember what was the platform on Editor. We were loading another new scene (non-additively). 

Yes, you are right, _Runnable is still there, even when is not being displayed on Hierarchy! So is super weird that the `Runnable.Instance` is causing the null reference exception. 

I will keep trying to reproduce the problem and if I have more data I will let you know!  (So far I was unable to get the same exception)

**Comment by david-rhodes** [comment] 2017-07-24 20:40
Unable to reproduce. Closing for now.

**Comment by mayofunk** [comment] 2017-11-14 22:48
Hi again, sorry for opening an old/closed ticket.

But, I got more of those exceptions, and at one moment I fixed using the `if (EqualityComparer<T>.Default.Equals(sm_Instance, null))` trick, but I realized that the reason of this problem is the current Singleton class that you are using.

The generic type constrain is `class`
````
    public class Singleton<T> where T : class {
````

And it should be `UnityEngine.Object` or something that inherits from UnityEngine.Object.
```
public class Singleton<T> where T : UnityEngine.Object {
```

In that way you will use the overloaded (by Unity)  `==` operator to compare correctly unity elements. Sometimes unity objects can be `"null"` instead of `null` and using the `class` == operator is not `good` enough. 

More info here: 
https://stackoverflow.com/questions/44991173/getcomponent-returning-null-instead-of-null/45028042#45028042
 
Greetings !

**Comment by david-rhodes** [comment] 2017-11-14 23:20
@mayofunk Woah--thanks for blowing my mind with this! I'll reopen the ticket so we can track/implement internally.

**Comment by david-rhodes** [comment] 2017-12-01 02:17
Fixed in #420

**Closed by david-rhodes** 2017-12-01 02:17 UTC
Labels: bug

**Comment by sethHex** [comment] 2020-03-19 17:50
Hello, I am still running into this issue now in Unity 2019. I load a scene normally, kick back to the menu, and then return to the scene only to see the MissingReferenceException for my AbstractMap. 
(One single map in the scene at all times)

**Comment by mayo-nesso** [comment] 2020-03-24 22:02
@sethHex are you getting a `MissingReferenceException` or a `NullReferenceException`?

**Comment by sethHex** [comment] 2020-03-25 14:49
MissingReferenceException
