### ISSUE TITLE
Camera not rendering when Unity is imported as a library in Android

### ISSUE THREAD

**Issue by tarakinsuide** [mapbox/mapbox-unity-sdk#981] opened 2018-08-24 07:20 UTC
Hi,

My mailbox unity app is working fine but I want to integrate it to my existing camera app.
The app in unity loads however the camera is not rendering. It shows extrusions and maps but no camera feed. Why so?

**Comment by jordy-isaac** [comment] 2018-08-24 16:04
Closing as a dupe of https://github.com/mapbox/mapbox-unity-sdk/issues/977

**Closed by jordy-isaac** 2018-08-24 16:04 UTC

**Comment by MuhammadAasharib** [comment] 2018-10-23 18:51
@tarakinsuide Have you found any solution? because I am facing same issue
