### ISSUE TITLE
HoloLens and MapBox issue

### ISSUE THREAD

**Issue by nosmirck** [mapbox/mapbox-unity-sdk#734] opened 2018-05-04 18:07 UTC
* Unity version:  2018.1.0.f2
  * Scripting Runtime Version: .Net 4.x Equivalent.
  * Scripting Backend: IL2CPP.
  * Api Compatibility Level: .NET 4.x
* Mapbox SDK version: 1.4.1
* The platform you're building to: UWP.
  * Target Device: HoloLens.
  * Build Type: D3D.
* A description of what you're trying to do:
Render the prefab "CitySimulatorMap" inside the Mixed Reality experience with HoloLens Device/Simulator.
* Steps to recreate the bug if appropriate:
  - Create a new project and include HoloToolkit and Examples from [here.](https://github.com/Microsoft/MixedRealityToolkit-Unity/releases)
  - Follow steps [here ](https://www.mapbox.com/mapbox-unity-sdk/docs/hololens-development.html)to configure the app for HoloLens.
  - Import Mapbox 1.4.1. Exclude GoogleARCore, MapboxAR, UnityARInterface and UnityARKitPlugin.
  - Setup Mapbox.
  - Add a new scene.
  - Apply all 3 options in Mixed Reality Toolkit > Configure.
  - Drag the prefab CitySimulatorMap.prefab from Assets/Mapbox/Prefabs to the scene
  
At this point, everything will work in the Editor.

Trying to compile with above settings will give errors of duplicated/ambiguous use of Description Attribute.

* Applying what was described in #485 by @BergWerkGIS will allow me to compile the project for VS

  - Add SQLite to the references
  - Build and deploy to Simulator and Device

* Issue:
Map is not rendered.

Here is the [Console Output](https://pastebin.com/Yyme7cxg) from Compilation to Deploy and Debug the App.

**Comment by BergWerkGIS** [comment] 2018-05-08 10:48
@nosmirck have you set your Mapbox access token?
Your log file contains:
> Error setting value to 'AccessToken' on 'Mapbox.Unity.MapboxConfiguration'.

Also, have you set the `Internet` Capabilities`?
Either in Unity or in the exported VS solution.

**Comment by nosmirck** [comment] 2018-05-08 18:11
> have you set your Mapbox access token?

Yes, it works fine on the Unity Editor. I did it during the step _Setup Mapbox._ from above

Here's a screenshot:
![image](https://user-images.githubusercontent.com/6027290/39774708-a53c86c8-52c9-11e8-9feb-2c1dead4e747.png)


>Also, have you set the Internet Capabilities`?
>Either in Unity or in the exported VS solution.

Yes, during the step _Apply all 3 options in Mixed Reality Toolkit > Configure._ from above.

I re-checked the permissions on the VS project, this is what I see:

![image](https://user-images.githubusercontent.com/6027290/39771969-e62f63b0-52c1-11e8-8498-fe5fcd70daa5.png)

**Comment by nosmirck** [comment] 2018-05-10 13:53
@BergWerkGIS great! no problem!

For now, I've been working on the rest of the simulation using a map I saved in runtime with the editor (made the map object once loaded a fbx) and I'm cool with that for now.

Just to share a bit what I'm doing:

I'm rendering a real time map on top of a table using HoloLens. On top of the map some data will be visualized by converting the data into a heat map texture and projected on top of the MapBox based on the location.

So, in the next few weeks I'll be working with all the rest of the project with a mocked map. There's no hurry, I have exactly 4 weeks from tomorrow to finish this project (it's actually a PoC) and I'd love to include the ability to zoom the map and change location.

Thanks for the support!

**Comment by YouAlwaysLoose** [comment] 2018-06-05 21:54
Hey there, are you guys were able to setup project with Hololens and MapBox?

**Comment by nosmirck** [comment] 2018-06-06 11:39
@YouAlwaysLoose no, I finished the rest of my PoC using a mocked map that I saved in editor runtime using this handy tool https://github.com/pharan/Unity-MeshSaver/blob/master/MeshSaver/Editor/MeshSaverEditor.cs

For the purpose of my PoC I believe I have enough, I'd like to have MapBox really load the current location and render the map properly so I can zoom in/out, change locations, etc. I'm still waiting for this bug to be fixed though.

@BergWerkGIS is there any ETA for this?

**Comment by BergWerkGIS** [comment] 2018-06-06 15:00
> @BergWerkGIS is there any ETA for this?

Working on it, but no ETA yet.
The change in Unity's behavior touches a lot more places than I had anticipated.
Especially `Mapbox.Json` (forked from `Newtonsoft.Json`) is a beast to tackle.

**Comment by Storm-Develop** [comment] 2018-06-06 15:11
@nosmirck Thank you for the quick reply.
@BergWerkGIS Awesome I am going to wait for it too.  Meanwhile will try to build & run the simple project.
If need something to test on Hololens please let me know.

**Comment by BergWerkGIS** [comment] 2018-06-06 15:21
> If need something to test on Hololens please let me know.

@Storm-Develop thanks, your help is very much appreciated 😄

**Comment by Storm-Develop** [comment] 2018-06-06 20:17
@BergWerkGIS =) Sorry I am not that familiar with MapBox structure yet to help more. I am just trying first to make it work with the simplest solution possible.
I was able to Build the project by following your  #485 steps. And it works great in the Unity.
However, in Hololens, I see nothing=( Seems like the map wasn't generated.

If I downgrade Unity to version 2017.1 is that going to help?

@nosmirck  when you referred that map didn't render what exactly you meant? Did you see a map in HoloLens?  I can't see anything except skybox.
![screen1](https://user-images.githubusercontent.com/11896104/41062532-b4997ba6-699b-11e8-9793-3f6359960de5.png)

**Comment by BergWerkGIS** [comment] 2018-06-07 14:05
@Storm-Develop 

> I was able to Build the project by following your #485 steps. And it works great in the Unity.
However, in Hololens, I see nothing=( Seems like the map wasn't generated.

The problem is that Unity and HoloLens (UWP - Universal Windows Platform) are running on different .Net framework versions which offer a **different set of APIs**.
Thus if something runs in Unity it is not for granted that the same thing will run on another platform, HoloLens in this case.
 
Because of the different APIs execution flow through code may follow different paths depending on the framework that's being used.

Take this simple example of string comparison:
https://github.com/mapbox/mapbox-unity-sdk/blob/803b32971671ef6f743382aaca895d4e0db0935f/sdkproject/Assets/Mapbox/Core/mapbox-sdk-cs/Platform/Response.cs#L273-L279

And we have _**a lot**_ of those `#if`/`#endif`s through our code.

Previously `WINDOWS_UWP` was defined by Unity when exporting to UWP.
That seems to have changed and our code as well as 3rd party libraries (eg Newtonsoft Json) need to be changed to account for that.

> If I downgrade Unity to version 2017.1 is that going to help?

Unfortunately I cannot tell: Unity's behavior has changed in one of the 2017.x releases but I don't know which as I haven't tried each and everyone.

**Comment by Storm-Develop** [comment] 2018-06-07 16:38
I see thank you for the detailed answer.
Maybe these can be useful.
https://forum.unity.com/threads/net-scripting-backend-and-visual-studio-2017-3-incompatibility.487833/#post-3191224
https://docs.microsoft.com/en-us/windows/uwp/gaming/missing-dot-net-apis-in-unity-and-uwp

So I guess the real question would be **how much time** it would take to fix the dependencies?

**Comment by BergWerkGIS** [comment] 2018-06-08 09:59
> So I guess the real question would be **how much time** it would take to fix the dependencies? 
> Is it possible that it can be done sometime next week?

@Storm-Develop I really can't tell as I'm hitting a `Catch 22`-like situation with a very simple problem already.

**Open to suggestions how to get past that.**

----

.NET framework version used by `UWP` doesn't have `DescriptionAttribute` so we define it ourselves and wrap it within `#if UNITY_WSA`:

```c#
#if UNITY_WSA
	[AttributeUsage(AttributeTargets.Field, AllowMultiple = false)]
	public class DescriptionAttribute : Attribute {
		private readonly string description;
		public string Description { get { return description; } }
		public DescriptionAttribute(string description) {
			this.description = description;
		}
	}
#endif
```

That produces the following `ambiguous reference` error in Editor
```
 error CS0104: `DescriptionAttribute' is an ambiguous reference between
`System.ComponentModel.DescriptionAttribute' and 
`Mapbox.VectorTile.Geometry.DescriptionAttribute'
```

as the API of the .NET framework version used by Editor does have the `DescriptionAttribute`.

So we wrap our definition into `#if !UNITY_EDITOR && UNITY_WSA` which makes the errors in Editor disappear.

However when I try to build to `Universal Windows Platform` with these settings
![image](https://user-images.githubusercontent.com/4549888/41151843-3b0a8ba4-6b12-11e8-9ba6-e8ff12ab2296.png)

I get `could not be found` error

```
error CS0246: 
The type or namespace name 'DescriptionAttribute' could not be found 
(are you missing a using directive or an assembly reference?)
``` 

as we are still in Editor and `#if !UNITY_EDITOR` blocks our implementation but export is done using the UWP version of .NET framework which doesn't have `DescriptionAttribute`.

❓ ❓ ❓ 

-----

My setup:

* Deleted all folders related to other AR implementations:
![image](https://user-images.githubusercontent.com/4549888/41151617-8fa2f0b2-6b11-11e8-9417-b0305e5cd4d0.png)
- Unity 2018.1.3.f1
- Platform: Universal Windows Platform
- Other Settings
  - Configuration
  ![](https://d2mxuefqeaa7sj.cloudfront.net/s_157216D0C93FF070A9D3D8F960110971FAC7CD3F00E2707671970A638F46B691_1528450929821_image.png)
- Publish Settings
  - Capabilites
    - ☑️ InternetClient
    - ☑️ SpatialPerception
- XR Settings:
  - Virtual Reality Supported:
    - Virtual Reality SDKs: Windows Mixed Reality

**Comment by Storm-Develop** [comment] 2018-06-08 13:32
@BergWerkGIS I see what if we just comment the description text for now?
Also maybe with #UNITY_WSA_10_0 it will work.
OR WITH #if UNITY_WSA && **ENABLE_DOTNET** && !UNITY_EDITOR
![screenshot_19](https://user-images.githubusercontent.com/11896104/41160582-cba24bb0-6af5-11e8-9ed3-9fb5eb81ae9d.png)
![screenshot_20](https://user-images.githubusercontent.com/11896104/41160859-7fc9a444-6af6-11e8-9787-28a63f653ba7.png)

**Comment by BergWerkGIS** [comment] 2018-06-08 13:51
@Storm-Develop 

> Also maybe with #UNITY_WSA_10_0 it will work.
OR WITH #if UNITY_WSA && ENABLE_DOTNET && !UNITY_EDITOR

Thanks for the ideas but I've already tried those and others (`UNITY_WINRT`, `NETFX_CORE`, `ENABLE_WINMD_SUPPORT`, `!UNITY_EDITOR`) and all possible permutations thereof.

Always the same problem: during different stages of the export Unity seems seems to use the Mono compiler and then for some other C# files the Microsoft compiler.

Also tried different runtimes and setting for the .NET Core override:
> * `None`: C# files are compiled using Mono compiler.
> * `Use .Net Core`: C# files are compiled using Microsoft compiler and .NET Core, you can use Windows Runtime API, but classes implemented in C# files aren’t accessible from the JS language. Note: when using API from Windows Runtime, it’s advisable to wrap the code with ENABLE_WINMD_SUPPORT define, because the API is only avaible when building to Universal Windows Platform, and it’s not available in Unity Editor.
> * `Use .Net Core Partially`: C# files not located in Plugins, Standard Assets, Pro Standard Assets folders are compiled using Microsoft compiler and .NET Core, all other C# files are compiled using Mono compiler. The advantage is that classes implemented in C# are accessible from the JS language. Note: You won’t be able to test .NET Core API in Unity Editor, because it doesn’t have access to .NET Core, so you’ll be able to test the API only when running Universal Windows App.

------

> what if we just comment the description text for now?

Yes, I had the same idea 😄 and that got me past the first hurdle.
Now working on module `vector-tile-cs`.

----

I'll keep this ticket updated.

**Comment by BergWerkGIS** [comment] 2018-06-11 13:12
@Storm-Develop @nosmirck 

I think I got an initial version working and it would be great if you could give it a spin and let me know if it works for you too.
Please see below for the settings I used and how to get that branch.

![hololens-quest-01](https://user-images.githubusercontent.com/4549888/41230394-e8c66bcc-6d7f-11e8-9d4c-a2068ac6abe9.gif)

-------

### My Settings

- **Unity@2018.1.3.f1**
- Platform: Universal Windows Platform
- Other Settings
  - Configuration: scripting backend `.NET`, **IL2CPP does not work!**
  ![](https://d2mxuefqeaa7sj.cloudfront.net/s_157216D0C93FF070A9D3D8F960110971FAC7CD3F00E2707671970A638F46B691_1528450929821_image.png)
- Publish Settings
  - Capabilites
    - ☑️ InternetClient
    - ☑️ SpatialPerception
- XR Settings:
  - Virtual Reality Supported:
    - Virtual Reality SDKs: Windows Mixed Reality 


![image](https://user-images.githubusercontent.com/4549888/41151843-3b0a8ba4-6b12-11e8-9ba6-e8ff12ab2296.png)


-----

### Branch `hololens-fixes`

As I've changed quite a few things (removed submodules, moved files around, ...) I suggest you clone to a dedicated local repo to avoid any conflicts:

Below command will clone just the `hololens-fixes` branch into a directory also called `hololens-fixes`:

```
git clone --branch hololens-fixes --single-branch --depth 1 git@github.com:mapbox/mapbox-unity-sdk.git hololens-fixes
```

-----

### Simple test

Open the `sdkproject` folder from the newly cloned repo in Unity and try to build (export) one of the examples (I went with `Globe`).

Don't forget to add `SQLite` to the main project when you build the exported project in Visual Studio:

```
Add Reference -> Universal Windows -> Extensions -> SQLite for Windows Universal Platform
```

![image](https://user-images.githubusercontent.com/4549888/39630012-517decde-4fae-11e8-813d-e3807b0866ec.png)

**Comment by Storm-Develop** [comment] 2018-06-11 14:18
@BergWerkGIS Millions of Thanks! It does work!
I tried the **Replace Features** Example 

![replacefeautures](https://user-images.githubusercontent.com/11896104/41237132-6a60202e-6d58-11e8-8c9b-0cd632aa7924.gif)


Just a small comment I didn't have SQLite for UWP so downloaded from the market store [https://marketplace.visualstudio.com/items?itemName=SQLiteDevelopmentTeam.SQLiteforUniversalWindowsPlatform](url)

**Comment by BergWerkGIS** [comment] 2018-06-11 14:51
@Storm-Develop Great! 🎉 🎆
Now you got something to work with. 

Thanks for testing  🙏 



Be aware thought that this is still work in progress and might need a few more weeks till it gets into `develop` branch and hopefully into the next release (still a lot of cleanup necessary).

> Just a small comment I didn't have SQLite for UWP so downloaded from the market place 

Oh yeah, thanks for the reminder. I forgot to mention that.

**Comment by timgoeij** [comment] 2018-06-24 23:14
@BergWerkGIS 

I have tried the same settings as you mentioned above in my own project and in an empty project and got the same atttribute errors in Unity 2018.1.6. Is there a possibillity for my to clone the Hololens-fixes? Last time I tried to clone the branch with above command, but  that it wasn't working before I wrote issue #875

**Comment by Storm-Develop** [comment] 2018-06-25 02:58
@timgoej Based on your error image you didn't get the hololens-fixes branch.  Just download the branch hololens-fixes manually as zip file.

**Comment by BergWerkGIS** [comment] 2018-06-25 07:10
@timgoeij I agree with @Storm-Develop: looks like you didn't get the `hololens-fixes` branch.

Either use this `git command`
```
git clone --branch hololens-fixes --single-branch --depth 1 git@github.com:mapbox/mapbox-unity-sdk.git hololens-fixes
```

or download https://github.com/mapbox/mapbox-unity-sdk/archive/hololens-fixes.zip

For both options make sure you are using a new target directory and **not** save/clone into an existing (SDK) one, which might also lead to those errors.

**Comment by timgoeij** [comment] 2018-06-27 07:34
@Storm-Develop and @BergWerkGIS 

Thanks both of you I wasn't sure if I downloaded the zip, mapbox should work properly.

**Comment by mayank-technical** [comment] 2018-07-09 11:20
@BergWerkGIS  You are amazing. Thanks for great help . I am able to run all the samples of mapbox. Thanks a ton.! Just need to know how you people record hololens screen?

**Comment by BergWerkGIS** [comment] 2018-07-09 12:01
Thanks @mayank-technical 🙏 

> Just need to know how you people record hololens screen?

By hitting `Record` in the `Device Portal` 😄:
https://docs.microsoft.com/en-us/windows/mixed-reality/using-the-windows-device-portal#mixed-reality-capture

**Comment by mayank-technical** [comment] 2018-07-10 03:06
Thanks a lot William.!! :)

**Comment by Roaringman** [comment] 2018-07-25 13:41
Hi!
Thank you for this fix. I got it working a few weeks ago on a worldscale AR application I'm working on. Now It suddenly stopped working again. Does anyone have an idea, what could be causing these errors? I´ve attached a screenshot of my console.

![grafik](https://user-images.githubusercontent.com/9324317/43203413-7265df50-901e-11e8-8a83-693d063656d6.png)

**Comment by BrentKingma** [comment] 2018-09-04 03:58
@BergWerkGIS hey, thanks for the work that you have been doing but do you know how long it will be for the mapbox to work with unity's il2cpp compiler?

**Comment by BergWerkGIS** [comment] 2018-09-07 10:09
Closing - PR [#945 UWP fixes (and more)](https://github.com/mapbox/mapbox-unity-sdk/pull/945) was merged.

**NOTE:**
UWP (Desktop, HoloLens, Windows Phone, ...) builds with *`Scripting Backend: IL2CPP`* still don't work - **only .NET backend does**.
Blocker here is https://github.com/mapbox/Mapbox.Json-unity (a fork of [Newtonsoft.Json](https://github.com/JamesNK/Newtonsoft.Json)) which emits dynamic compiler code which does not work with IL2CPP.

**Closed by BergWerkGIS** 2018-09-07 10:09 UTC
Labels: support

**Comment by LukeHackett12** [comment] 2019-03-03 02:25
Hi, I was wondering if this is still an ongoing issue. I am attempting to use mapbox on hololens and even with all the permissions set I still get this error:

```
Exception thrown: 'SQLite4Unity3d.SQLiteException' in Assembly-CSharp.dll
error:14090086:lib(20):func(144):reason(134)
Setting up 1 worker threads for Enlighten.

  Thread -> id: 634 -> priority: 1 

Mapbox.Unity.MapboxAccess+InvalidTokenException: StatusNotYetSet
```
 Any help would be appreciated!

**Comment by Toducs** [comment] 2019-04-11 19:35
Hi, I was trying the same and after digging for a few hours... i found that the problem is that the PRAGMA command send to the sqlite was actually returning a row, and because it get executed with ExecuteNonQuery command it was not expecting a row results, what cause raise the error. I was able to pass that by chaging the line 2152 of the \Assets\Mapbox\Core\mapbox-sdk-cs\Platform\SQLite\SQLite.cs file as `if (r == SQLite3.Result.Done || r == SQLite3.Result.Row)`.
However now I have other problem and is that for some reason the webrequest to get the token is not working. It seem to be related to the UnityWebRequest getting Unknow error... I am trying to figure it out.

**Comment by LukeHackett12** [comment] 2019-04-11 19:47
You have to substitute unityWebRequests with normal c# HttpRequests, at least that's what I've done elsewhere and it's worked to get Web information.

**Comment by Toducs** [comment] 2019-04-12 14:55
Hooo that make sense. Thank you very much.

**Comment by katsuwo** [comment] 2020-07-12 15:16
Hello.
Has anyone run Mapbox sdk for unity on Hololens2?
My test project is working correctly in the Unity Editor, but the
A CS0104 error occurs during the build phase.
From here I learned that MapBox SDK for unity does not support IL2CPP, is this situation still the same?
Is there a way to run mapboxsdk in Hololens2?

Thank you.

**Comment by lukemadera** [comment] 2021-04-21 15:17
@BergWerkGIS Thanks for your work on this; any update on IL2CPP, or is Mapbox still not usable for UWP?

**Comment by NHarishGit** [comment] 2021-10-23 22:03
UNITY 2019.4.31f with MAPBOX v2.1.1 SDK, still the same errors, cannot build for UWP with I2LCPP (mandated by UNITY):

"Assets\Mapbox\Core\mapbox-sdk-cs\MapMatching\MapMatchingParameters.cs(15,4): error CS0104: 'Description' is an ambiguous reference between 'Mapbox.VectorTile.Geometry.DescriptionAttribute' and 'System.ComponentModel.DescriptionAttribute'"

Any one has taken an effort to fix it  or a WorkAround for now ?

**Comment by emartinDesignInteractive** [comment] 2021-10-23 22:07
> UNITY 2019.4.31f with MAPBOX v2.1.1 SDK, still the same errors, cannot build for UWP with I2LCPP (mandated by UNITY):
> 
> "Assets\Mapbox\Core\mapbox-sdk-cs\MapMatching\MapMatchingParameters.cs(15,4): error CS0104: 'Description' is an ambiguous reference between 'Mapbox.VectorTile.Geometry.DescriptionAttribute' and 'System.ComponentModel.DescriptionAttribute'"
> 
> Any one has taken an effort to fix it or a WorkAround for now ?

Would recommend looking into Microsoft's Maps for Unity plugin, depending on your use case.

https://github.com/microsoft/MapsSDK-Unity

**Comment by tvasilopoulou** [comment] 2021-11-18 11:26
Hello everyone,
I have been trying to load a simple map prefab using Mapbox with:

- Unity Version: 2019.3.5f1
- Mapbox version: 2.1.1
- AR Foundation package 2.1.8

I have also deleted all AR related directories from the mapbox package and set all "Description" occurrences to refer to System.ComponentModel.  In MapboxAccountsUnity.dll, I have checked the WSAPlayer checkbox in the inspector panel. Finally, after building for UWP as shown in the picture below, I have added the SQLite reference.
![Screenshot_30](https://user-images.githubusercontent.com/46397271/142406096-a216b200-c3b7-465d-bd56-c214dda44923.png)

I have the same problem as @nosmirck described in https://github.com/mapbox/mapbox-unity-sdk/issues/734#issuecomment-395201914, meaning I can successfully deploy to Hololens but on Debug mode I get similar logs as shown here:  
![20211117_122503_HoloLens](https://user-images.githubusercontent.com/46397271/142406407-06f02617-fd0b-4698-86a2-8fc7dc0116ae.jpg)

Most important error in the logs is: Rethrow as JsonSerializationException: Error setting value to 'AccessToken' on 'Mapbox.Unity.MapboxConfiguration'.
  at Mapbox.Json.Serialization.ExpressionValueProvider.SetValue

but the token I provide in the editor is valid. In the Project settings my Scripting backend in IL2CPP which I cannot change but the API compatibility level is .NET 4.x.

Does anyone know how I can manage rendering the map on Hololens and resolving the NullReferenceException? Thank you!

**Comment by mertusta1996** [comment] 2022-07-13 21:49
For Hololens-2 and Mapbox in Unity UWP, try this repo ;
https://github.com/mertusta1996/Mapbox-Hololens-2-Unity-UWP-

**Comment by NHarishGit** [comment] 2022-07-13 22:03
> For Hololens-2 and Mapbox in Unity UWP, try this repo ; [https://github.com/mertusta1996/Mapbox-Hololens-2-Unity-UWP-](url)

The link is NOT working for me

**Comment by mertusta1996** [comment] 2022-07-13 22:13
I fixed the link sorry 👍 
https://github.com/mertusta1996/Mapbox-Hololens-2-Unity-UWP-

**Comment by mertusta1996** [comment] 2022-07-13 22:19
> > For Hololens-2 and Mapbox in Unity UWP, try this repo ; [https://github.com/mertusta1996/Mapbox-Hololens-2-Unity-UWP-](url)
> 
> The link is NOT working for me

I fixed the link sorry 👍
https://github.com/mertusta1996/Mapbox-Hololens-2-Unity-UWP-
